language: r
cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true

r:
  - oldrel
  - release
  - devel

notifications:
  email:
    recipients:
      -alerts+sosinsk7@msu.edu
    on_success: change
    on_failure: change